/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

void generate_interrupt(void)
{
       uint32_t *pSTIR = (uint32_t *)0xE000EF00;
       uint32_t *pISER0 = (uint32_t *)0xE000E100;

       // enable IRQ3
       *pISER0 |= (1<<3);

       // generate SWI
       *pSTIR = (0x3);

}


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	printf("heeee\n");

	generate_interrupt();

	printf("hooooo\n");
	for(;;);
}

void RTC_WKUP_IRQHandler(void)
{
	printf("in handler mode\n");
}




