/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define USART3_IRQ_NUMBER	39
int main(void)
{
	uint32_t *pNVIC_IPSR;
	uint32_t *pNVIC_ISER;
	uint32_t data;
	// 1. Manually pend the pending bit for the USART3 IRQ number in NVIC.
	// USART3 IRQ number is 39.

	printf("hello\n");

	pNVIC_IPSR = (uint32_t *)0xE000E200 + (USART3_IRQ_NUMBER/32);
	*pNVIC_IPSR |= ( 1 << (USART3_IRQ_NUMBER % 32));

	pNVIC_ISER = (uint32_t *)0xE000E100 + (USART3_IRQ_NUMBER/32);
	*pNVIC_ISER |= ( 1 << (USART3_IRQ_NUMBER % 32));

    /* Loop forever */
	for(;;);
}

void USART3_IRQHandler(void)
{
	printf("usart3\n");
	while(1);
}
