/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define SVC_ADD		(36)
#define SVC_SUB		(37)
#define SVC_MULT	(38)
#define SVC_DIV		(39)

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int SVC_math(int x, int y, int op)
{
	int ret;

	if (op == SVC_ADD) {
		__asm__("SVC 36");
	} else if (op == SVC_SUB) {
		__asm__("SVC 37");
	} else if (op == SVC_MULT) {
		__asm__("SVC 38");
	} else if (op == SVC_DIV) {
		__asm__("SVC 39");
	}

	__asm__ volatile("MOV %0, R0":"=r"(ret));

	return ret;
}

int main(void)
{
	int ret;
    /* Loop forever */

	ret = SVC_math(2, 3, SVC_ADD);
	printf("add: %d\n", ret);

	ret = SVC_math(10, 7, SVC_SUB);
	printf("sub: %d\n", ret);

	ret = SVC_math(16, 2, SVC_MULT);
	printf("mult: %d\n", ret);

	ret = SVC_math(50, 10, SVC_DIV);
	printf("div: %d\n", ret);

	for(;;);
}

__attribute__((naked)) void SVC_Handler(void)
{
	__asm__("MRS R0, MSP");
	__asm__("PUSH {R0, R1, R2, R3, R12, LR}");
	__asm__("BL __SVC_Handler");
	__asm__("POP {R0, R1, R2, R3, R12, LR}");
	__asm__("BX LR");
}

void __SVC_Handler(uint32_t *msp_number)
{
	uint32_t * pMSP = (uint32_t * )msp_number;
	uint32_t * pINST;
	uint32_t SVC_opcode;
	uint32_t ret;
	uint32_t arg0;
	uint32_t arg1;

	pINST = (uint32_t *)(pMSP[6] -2);
	SVC_opcode = (*pINST & 0xFF);

	arg0 = (uint32_t)(pMSP[0]);
	arg1 = (uint32_t)(pMSP[1]);

	if (SVC_opcode == SVC_ADD) {
		pMSP[0] = arg0 + arg1;
	} else if (SVC_opcode == SVC_SUB) {
		pMSP[0] = arg0 - arg1;
	} else if (SVC_opcode == SVC_MULT) {
		pMSP[0] = arg0 * arg1;
	} else if (SVC_opcode == SVC_DIV) {
		pMSP[0] = arg0 / arg1;
	} else {
		pMSP[0] = -1;
	}
}


