/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define SCB_SHCSR_BASE	(0xE000ED24)
#define SRAM_BASE	(0x20000000)
#define PERI_BASE	(0x40000000)

#define SCB_UFSR_BASE	(0xE000ED2A)
#define SCB_MMSR_BASE	(0xE000ED28)
#define SCB_CCR_BASE	(0xE000ED14)

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int divide_function(int x, int y)
{
	return x/y;
}

int main(void)
{
	uint32_t *pSHCSR;
	uint32_t *pSRAM;
	uint32_t *pSCB_CCR;

	printf("hello\n");

	void (*func_ptr)(void);

	int data = 10;
	// 1. enable all configurable system exceptions.

	pSHCSR = (uint32_t *)SCB_SHCSR_BASE;
	*pSHCSR |= (1<<18)|(1<<17)|(1<<16); // enable Usage fault, Bus fault, Mem fault.

	// 2. implement fault handlers

	/*
	// 3. force the processor to execute some undefeined instruction.
	pSRAM = (uint32_t *)SRAM_BASE;
	*pSRAM = 0xFFFF0000; // undefined instruction.
	// pSRAM = (uint32_t *)PERI_BASE;


	func_ptr = (void *)((void *)pSRAM + 1);
	func_ptr();
*/
	pSCB_CCR = (uint32_t *)SCB_CCR_BASE;
	printf("default CCR: %08x\n", *pSCB_CCR);
	*pSCB_CCR &= ~(0x1 << 4);
	printf("disable div zero CCR: %08x\n", *pSCB_CCR);

	// 3. divided by zero.
	divide_function(10, 0);

	printf("bye\n");
	//data /= 0;
	// 4. analyze the faults.
    /* Loop forever */
	for(;;);
}

void MemManage_Handler(void)
{
	printf("Mem fault");
	while(1);

}
void BusFault_Handler(void)
{
	printf("Bus fault");
	while(1);
}

__attribute__((naked)) void UsageFault_Handler(void)
{
	__asm__("MRS R0, MSP");
	__asm__("B __UsageFault_Handler");
}

void __UsageFault_Handler(uint32_t *msp_value)
{
	uint32_t * pMSP = (uint32_t *)msp_value;


	// print stack frame of previous context.
	printf("pMSP: %p\n", pMSP);
	printf("R0: %08x\n", pMSP[0]);
	printf("R1: %08x\n", pMSP[1]);
	printf("R2: %08x\n", pMSP[2]);
	printf("R3: %08x\n", pMSP[3]);
	printf("R12: %08x\n", pMSP[4]);
	printf("LR: %08x\n", pMSP[5]);
	printf("PC: %08x\n", pMSP[6]);
	printf("XPSR: %08x\n", pMSP[7]);

	uint32_t * pUFSR = (uint32_t *)SCB_UFSR_BASE;
	uint32_t data = *pUFSR;
	printf("Usage fault status: %08x\n", data);
	printf("usage fault\n");
	while(1);
}


void HardFault_Handler(void)
{
	printf("Hard fault");
	while(1);
}
